name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-dept: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
        
    - name: auth to docker hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD    

    - name: build image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t monolith394/docker-graphql:$NEW_VERSION .
        docker build -t monolith394/docker-graphql:latest .

    - name: push image to docker hub
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push monolith394/docker-graphql:$NEW_VERSION
        docker push monolith394/docker-graphql:latest




        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
